[package]
name = "cleric"
version = "0.1.0"
authors = ["Brandon High <highb@github"]
edition = "2018"

[dependencies]
serenity = "0.11"
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
