[package]
name = "cleric"
version = "0.1.0"
authors = ["Brandon High <highb@github"]
edition = "2021"

[dependencies]
serenity = "0.10"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
